apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-configmap
data:
  Y9lMot3StTop8wa7ArWJNfPxF1_Q5ucv4On0nYENAnU: "Y9lMot3StTop8wa7ArWJNfPxF1_Q5ucv4On0nYENAnU.kgEWgLTPNmT78vzeXvMcVEAMT2eenkcnCw2wo99_Mpw"
