apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    # - host: my-kubernetes-registry.chickenkiller.com
    - http:
        paths:
          - path: /.well-known/acme-challenge/wahU3z6lSskFGEkjpolnNk2hZG4n5vi7jtVe9OVebdU
            pathType: Exact
            backend:
              service:
                name: tls-service
                port:
                  number: 80
