apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.67.240-192.168.67.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - my-ip-pool
