sharedNamespace: {{ namespaces.application.name }}
# applicationHost: my-kubernetes.chickenkiller.com
applicationHost: kubernetes-yep.duckdns.org


frontend:
  configmap:
    name: frontend-configmap
    REACT_APP_API_URL: "/api"

  deployment:
    name: frontend-deployment
    replicas: {{ replica }}
    podName: frontend-pod
    containerName: frontend-container
    # image: ghcr.io/vlad-yarko/my-kubernetes-frontend:1.0.1
    image: kubernetes-yep-registry.duckdns.org/my-kubernetes/frontend:prod
    containerPort: 8080

  service:
    name: frontend-service
    port: 8080

  ingressRoute:
    name: frontend-ingressroute
  
  secret: {{ args.environment }}

secret_tls:
  name: secret-tls

middleware_tls:
  name: middleware-tls

harborSecret:
  name: harbor-secret
