helmChart:
  # path: ../chart
  repo: oci://ghcr.io/vlad-yarko/my-kubernetes/backend-chart
  chartVersion: 1.0.0
  releaseName: my-kubernetes-backend-{{ args.environment }}
  namespace: {{ namespaces.application.name }}
  # namespace: default
  output: helm-rendered.yaml
  skipPrePull: true
  # valuesFiles: 
  #   - helm-values-{{ args.environment }}.yaml
