annotations:
  org.opencontainers.image.maintainer: vlad-yarko
  org.opencontainers.image.source: https://github.com/vlad-yarko/my-kubernetes
apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: traefik
  repository: https://traefik.github.io/charts
  version: 20.8.0
description: Ingress chart of my-kubernetes
home: https://github.com/vlad-yarko/my-kubernetes
maintainers:
- email: vladislavv44444@gmail.com
  name: vlad-yarko
name: ingress-chart
sources:
- https://github.com/vlad-yarko/my-kubernetes
type: application
version: 1.0.0
