apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-prometheus-service-monitor
  namespace: {{ .Values.sharedNamespace }}
  # labels:
  #   release: prometheus  # важливо для Helm-к чарта kube-prometheus-stack
  labels:
    release: my-kubernetes-prometheus-{{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.service.name }}
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
