helmChart:
  repo: oci://kubernetes-yep-registry.duckdns.org/my-kubernetes/loki-chart-k
  chartVersion: 1.0.0
  releaseName: my-kubernetes-loki-{{ args.environment }}
  # namespace: {{ namespaces.application.name }}
  # namespace: default
  namespace: my-kubernetes-monitoring
  output: helm-rendered.yaml
  # skipPrePull: true
  # valuesFiles: 
  #   - helm-values-{{ args.environment }}.yaml
