apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-staging
  namespace: {{ .Values.sharedNamespace }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-staging
  data:
  - secretKey: REACT_PUBLIC_ANTON
    remoteRef:
      key: "staging"
      property: "REACT_PUBLIC_ANTON"
