helmChart:
  # path: ../chart
  repo: oci://kubernetes-yep-registry.duckdns.org/my-kubernetes/database-chart-k
  # repo: oci://ghcr.io/vlad-yarko/my-kubernetes/database-chart
  chartVersion: 1.0.0
  releaseName: my-kubernetes-database-{{ args.environment }}
  # namespace: {{ namespaces.application.name }}
  # namespace: default
  namespace: my-kubernetes-application
  output: helm-rendered.yaml
  # skipPrePull: true
  # values: 
  #   - helm-values-{{ args.environment }}.yaml
