apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-postgres-exporter-sm
  labels:
    release: my-kubernetes-prometheus-{{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: prometheus-postgres-exporter-service
  endpoints:
    - port: metrics
      interval: 15s
      metricRelabelings:
        - sourceLabels: [__address__]
          targetLabel: host
