apiVersion: v1
kind: Service
metadata:
  name: prometheus-postgres-exporter-service
  labels:
    app: prometheus-postgres-exporter-service
spec:
  selector:
    app: prometheus-postgres-exporter-pod
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
