apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.sharedNamespace }}
  labels:
    app: {{ .Values.backend.service.name }}
spec:
  selector:
    app: {{ .Values.backend.deployment.podName }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.deployment.containerPort }}
