sharedNamespace: my-kubernetes-application


frontend:
  configmap:
    name: frontend-configmap
    REACT_APP_API_URL: "/api"

  deployment:
    name: frontend-deployment
    replicas: 2
    podName: frontend-pod
    containerName: frontend-container
    image: ghcr.io/vlad-yarko/my-kubernetes-frontend:1.0.1
    containerPort: 8080

  service:
    name: frontend-service
    port: 8080

  ingressRoute:
    name: frontend-ingressroute
