helmChart:
  repo: oci://ghcr.io/vlad-yarko/my-kubernetes/my-kubernetes-ingress-chart
  # chartName: my-kubernetes-ingress-chart
  chartVersion: 1.0.0
  releaseName: my-kubernetes-ingress-{{ args.environment }}
  namespace: {{ namespaces.ingress.name }}
  # namespace: default
  output: helm-rendered.yaml
  skipPrePull: true
  # values: 
  #   - helm-values-{{ args.environment }}.yaml
