# entryPoints:
#   web:
#     address: ":80"
#   websecure:
#     address: ":443"

# additionalArguments:
#   - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
#   - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
#   - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
traefik:
  additionalArguments:
    - "--serverstransport.insecureskipverify=true"
  tlsOptions:
    default:
      minVersion: VersionTLS12
  tlsStore:
    default:
      defaultCertificate:
        secretName: registry-secret-tls
