apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harbor_secret.name }}
  namespace: {{ .Values.sharedNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    YWRtaW46YnVzaW5lc3M=
