apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_tls.name }}
  namespace: {{ .Values.sharedNamespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDoTCCAyegAwIBAgISBryCNdyWbehyT5exD9gEjyGxMAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    ODAeFw0yNTEyMDcyMDE3MTdaFw0yNjAzMDcyMDE3MTZaMCUxIzAhBgNVBAMTGmt1
    YmVybmV0ZXMteWVwLmR1Y2tkbnMub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
    QgAEybOzVoFhtasqWF/n6l0UXZ+Odx6a2u9DcjM/bSsdjczq3+FTUe4YceHg8YvE
    eq0GBROnCQtEgwlrJ5p8uF/97KOCAigwggIkMA4GA1UdDwEB/wQEAwIHgDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUVBLkGbqGwFAb60qEWvNCvKzZGOcwHwYDVR0jBBgwFoAUjw0TovYuftFQbDMY
    OF1ZjiNykcowMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAChhZodHRwOi8vZTgu
    aS5sZW5jci5vcmcvMCUGA1UdEQQeMByCGmt1YmVybmV0ZXMteWVwLmR1Y2tkbnMu
    b3JnMBMGA1UdIAQMMAowCAYGZ4EMAQIBMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6
    Ly9lOC5jLmxlbmNyLm9yZy81MC5jcmwwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAA
    dQBJnJtp3h187Pw23s2HZKa4W68Kh4AZ0VVS++nrKd34wwAAAZr6q7TTAAAEAwBG
    MEQCIBAfrwdEhGPAMIeLW5RMkrWp+6hnFmrYnGbJu2/kD6mCAiAOIg44j82ROTB2
    ezV6eAm85F9y2y6pPoFFpiCjuhgVDQB3AA5XlLzzrqk+MxssmQez95Dfm8I9cTIl
    3SGpJaxhxU4hAAABmvqrtMYAAAQDAEgwRgIhAOmJobLXn2LoGNMFB0d8K+LZ7eT4
    OHWPaZ29dRxDP/YbAiEA659D1SNRsyRixJCCyLJVBm4oWU3Nh8c91sQOr2pHCIkw
    CgYIKoZIzj0EAwMDaAAwZQIxAMLxXtNMDXdmeiv5jjHhXJzY+/T08ePjnlgJwVM4
    kJsF70vJUya5lGIvJJtJL1nKxwIwbRhPHzci45FhCfmpKs/LZownMOZny1wX3Wmv
    noRo5vlk5Yr2ThE2QGE2tr5ynDKJ
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEVjCCAj6gAwIBAgIQY5WTY8JOcIJxWRi/w9ftVjANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
    Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
    Fw0yNzAzMTIyMzU5NTlaMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
    bmNyeXB0MQswCQYDVQQDEwJFODB2MBAGByqGSM49AgEGBSuBBAAiA2IABNFl8l7c
    S7QMApzSsvru6WyrOq44ofTUOTIzxULUzDMMNMchIJBwXOhiLxxxs0LXeb5GDcHb
    R6EToMffgSZjO9SNHfY9gjMy9vQr5/WWOrQTZxh7az6NSNnq3u2ubT6HTKOB+DCB
    9TAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMB
    MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFI8NE6L2Ln7RUGwzGDhdWY4j
    cpHKMB8GA1UdIwQYMBaAFHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEB
    BCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzATBgNVHSAE
    DDAKMAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5j
    ci5vcmcvMA0GCSqGSIb3DQEBCwUAA4ICAQBnE0hGINKsCYWi0Xx1ygxD5qihEjZ0
    RI3tTZz1wuATH3ZwYPIp97kWEayanD1j0cDhIYzy4CkDo2jB8D5t0a6zZWzlr98d
    AQFNh8uKJkIHdLShy+nUyeZxc5bNeMp1Lu0gSzE4McqfmNMvIpeiwWSYO9w82Ob8
    otvXcO2JUYi3svHIWRm3+707DUbL51XMcY2iZdlCq4Wa9nbuk3WTU4gr6LY8MzVA
    aDQG2+4U3eJ6qUF10bBnR1uuVyDYs9RhrwucRVnfuDj29CMLTsplM5f5wSV5hUpm
    Uwp/vV7M4w4aGunt74koX71n4EdagCsL/Yk5+mAQU0+tue0JOfAV/R6t1k+Xk9s2
    HMQFeoxppfzAVC04FdG9M+AC2JWxmFSt6BCuh3CEey3fE52Qrj9YM75rtvIjsm/1
    Hl+u//Wqxnu1ZQ4jpa+VpuZiGOlWrqSP9eogdOhCGisnyewWJwRQOqK16wiGyZeR
    xs/Bekw65vwSIaVkBruPiTfMOo0Zh4gVa8/qJgMbJbyrwwG97z/PRgmLKCDl8z3d
    tA0Z7qq7fta0Gl24uyuB05dqI5J1LvAzKuWdIjT1tP8qCoxSE/xpix8hX2dt3h+/
    jujUgFPFZ0EVZ0xSyBNRF3MboGZnYXFUxpNjTWPKpagDHJQmqrAcDmWJnMsFY3jS
    u1igv3OefnWjSQ==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgJo0baCpGx+kqnNcW
    n8VuxAtjuzDMw3G+yFcd3WQlnw6hRANCAATJs7NWgWG1qypYX+fqXRRdn453Hpra
    70NyMz9tKx2NzOrf4VNR7hhx4eDxi8R6rQYFE6cJC0SDCWsnmny4X/3s
    -----END PRIVATE KEY-----
