apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-middleware
  namespace: {{ .Values.sharedNamespace }}
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /grafana
