apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_tls.name }}
  namespace: {{ .Values.sharedNamespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDuzCCA0GgAwIBAgISBpD02I4BJpANq/rT+q3nNMfhMAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    ODAeFw0yNTEyMDcyMDUwMTBaFw0yNjAzMDcyMDUwMDlaMC4xLDAqBgNVBAMTI2t1
    YmVybmV0ZXMteWVwLXJlZ2lzdHJ5LmR1Y2tkbnMub3JnMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAETQw3IH43aJZ/Ml4gLQ+35FG6QTVN6bt//P05mC/9ekPi5Lx8
    w1gQ80lV9QVlPZ2nMbxQRba6S5Xk3yf9oupWHKOCAjkwggI1MA4GA1UdDwEB/wQE
    AwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIw
    ADAdBgNVHQ4EFgQUGpi4cuuOunfjYhOjQrVpE7OJ+JMwHwYDVR0jBBgwFoAUjw0T
    ovYuftFQbDMYOF1ZjiNykcowMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAChhZo
    dHRwOi8vZTguaS5sZW5jci5vcmcvMC4GA1UdEQQnMCWCI2t1YmVybmV0ZXMteWVw
    LXJlZ2lzdHJ5LmR1Y2tkbnMub3JnMBMGA1UdIAQMMAowCAYGZ4EMAQIBMC0GA1Ud
    HwQmMCQwIqAgoB6GHGh0dHA6Ly9lOC5jLmxlbmNyLm9yZy85OC5jcmwwggEMBgor
    BgEEAdZ5AgQCBIH9BIH6APgAdgAWgy2r8KklDw/wOqVF/8i/yCPQh0v2BCkn+Ocf
    MxP1+gAAAZr6yc7VAAAEAwBHMEUCIQCkIvW9nB4lJq7wST2OQe7iooPrn1lcdJ8h
    U6x3UhnlqgIgbBcmGm0TL2HryCI4sAlNVFBp3a2V4Wz4kuWYRojnbNEAfgAai51p
    SleYyJmgyoi99I/AtFZgzMNgDR9x9Gn/x9GsowAAAZr6ydJyAAgAAAUAIYH/XgQD
    AEcwRQIhANc8kileEnwUDUqYiyngiAdN/gfK8PQgXVxYJuGyRQiRAiA3Zg0Bf8RB
    KmWxFoZGui7Om40TmWpzwG8ZEv7rOJnTFTAKBggqhkjOPQQDAwNoADBlAjEAlvQh
    D4SyGcNiDOiwC0aZKpmN9SafJjEBi+BhaPddHWIJHfRpfVn+83hh1e5OqcXRAjBS
    mWszFpjqG+MPqqP+FQ2Wp7k0fJr0PXMkG617/c8UjHRtk2Tani/I+rqn2ObihFI=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEVjCCAj6gAwIBAgIQY5WTY8JOcIJxWRi/w9ftVjANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
    Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
    Fw0yNzAzMTIyMzU5NTlaMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
    bmNyeXB0MQswCQYDVQQDEwJFODB2MBAGByqGSM49AgEGBSuBBAAiA2IABNFl8l7c
    S7QMApzSsvru6WyrOq44ofTUOTIzxULUzDMMNMchIJBwXOhiLxxxs0LXeb5GDcHb
    R6EToMffgSZjO9SNHfY9gjMy9vQr5/WWOrQTZxh7az6NSNnq3u2ubT6HTKOB+DCB
    9TAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMB
    MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFI8NE6L2Ln7RUGwzGDhdWY4j
    cpHKMB8GA1UdIwQYMBaAFHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEB
    BCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzATBgNVHSAE
    DDAKMAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5j
    ci5vcmcvMA0GCSqGSIb3DQEBCwUAA4ICAQBnE0hGINKsCYWi0Xx1ygxD5qihEjZ0
    RI3tTZz1wuATH3ZwYPIp97kWEayanD1j0cDhIYzy4CkDo2jB8D5t0a6zZWzlr98d
    AQFNh8uKJkIHdLShy+nUyeZxc5bNeMp1Lu0gSzE4McqfmNMvIpeiwWSYO9w82Ob8
    otvXcO2JUYi3svHIWRm3+707DUbL51XMcY2iZdlCq4Wa9nbuk3WTU4gr6LY8MzVA
    aDQG2+4U3eJ6qUF10bBnR1uuVyDYs9RhrwucRVnfuDj29CMLTsplM5f5wSV5hUpm
    Uwp/vV7M4w4aGunt74koX71n4EdagCsL/Yk5+mAQU0+tue0JOfAV/R6t1k+Xk9s2
    HMQFeoxppfzAVC04FdG9M+AC2JWxmFSt6BCuh3CEey3fE52Qrj9YM75rtvIjsm/1
    Hl+u//Wqxnu1ZQ4jpa+VpuZiGOlWrqSP9eogdOhCGisnyewWJwRQOqK16wiGyZeR
    xs/Bekw65vwSIaVkBruPiTfMOo0Zh4gVa8/qJgMbJbyrwwG97z/PRgmLKCDl8z3d
    tA0Z7qq7fta0Gl24uyuB05dqI5J1LvAzKuWdIjT1tP8qCoxSE/xpix8hX2dt3h+/
    jujUgFPFZ0EVZ0xSyBNRF3MboGZnYXFUxpNjTWPKpagDHJQmqrAcDmWJnMsFY3jS
    u1igv3OefnWjSQ==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgv0SijzueqTFqotjx
    3Oaiu1BSgmlRiuWFBnAj6L+hKf2hRANCAARNDDcgfjdoln8yXiAtD7fkUbpBNU3p
    u3/8/TmYL/16Q+LkvHzDWBDzSVX1BWU9nacxvFBFtrpLleTfJ/2i6lYc
    -----END PRIVATE KEY-----
