apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ingress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-ingress-pod
  template:
    metadata:
      labels:
        app: my-ingress-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.0
