annotations:
  org.opencontainers.image.maintainer: vlad-yarko
  org.opencontainers.image.source: https://github.com/vlad-yarko/my-kubernetes
apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 70.7.0
description: prometheus chart of my-kubernetes
home: https://github.com/vlad-yarko/my-kubernetes
maintainers:
- email: vladislavv44444@gmail.com
  name: vlad-yarko
name: prometheus-chart-k
sources:
- https://github.com/vlad-yarko/my-kubernetes
type: application
version: 1.0.7
