sharedNamespace: my-kubernetes-application
# applicationHost: my-kubernetes.chickenkiller.com
applicationHost: my-kubernetes.mooo.com


secret_tls:
  name: secret-tls


middleware_tls:
  name: middleware-tls
