apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-kong
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geteway-pod-kong
  template:
    metadata:
      labels:
        app: geteway-pod-kong
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.0
