apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secretName }}
  namespace: {{ .Values.sharedNamespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:1234@{{ .Release.Name }}-postgresql-primary.{{ .Values.sharedNamespace }}.svc.cluster.local:5432/postgres" # BAAAAAD
  DB_HOST: "{{ .Release.Name }}-postgresql-primary.{{ .Values.sharedNamespace }}.svc.cluster.local"
