sharedNamespace: {{ namespaces.monitoring.name }}
applicationHost: kubernetes-yep.duckdns.org


config:
  clients:
    - url: http://my-kubernetes-loki-{{ args.environment }}-gateway.my-kubernetes-monitoring.svc.cluster.local:80/loki/api/v1/push



promtail:
  config:
    clients:
      - url: http://my-kubernetes-loki-{{ args.environment }}-gateway.my-kubernetes-monitoring.svc.cluster.local:80/loki/api/v1/push

