apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-production
  namespace: {{ .Values.sharedNamespace }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-production
#   data:
#   - secretKey: api-key
#     remoteRef:
#       key: "dev"
#       property: "api-key"
  data:
  - secretKey: REACT_PUBLIC_ANTON
    remoteRef:
      key: "production"
      property: "REACT_PUBLIC_ANTON"
