apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  # name: {{ .Values.harborSecret.name }}
  namespace: {{ .Values.sharedNamespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "kubernetes-yep-registry.duckdns.org": {
          "username": "admin",
          "password": "business",
          "auth": "YWRtaW46YnVzaW5lc3M="
        }
      }
    }
